const quizzes = [
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: "easy",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/d.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/e.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/b.jpg",
    questions: 10,
    plays: 725,
    label: "medium",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/d.jpg",
    questions: 10,
    plays: 725,
    label: "medium",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/e.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/f.jpg",
    questions: 10,
    plays: 725,
    label: "Hard",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/g.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/h.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/i.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/k.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/m.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
];

export default quizzes;
