const quizzes = [
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: "easy",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: "medium",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: "medium",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: "Hard",
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  {
    id: 1,
    title: "Quiz on Topic 1",
    thumbnail: "/a.jpg",
    questions: 10,
    plays: 725,
    label: null,
    questionSet: [
      {
        question: "What is the answer to question 1 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 1" },
          { id: "b", text: "Option B for question 1" },
          { id: "c", text: "Option C for question 1" },
          { id: "d", text: "Option D for question 1" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 2 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 2" },
          { id: "b", text: "Option B for question 2" },
          { id: "c", text: "Option C for question 2" },
          { id: "d", text: "Option D for question 2" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 3 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 3" },
          { id: "b", text: "Option B for question 3" },
          { id: "c", text: "Option C for question 3" },
          { id: "d", text: "Option D for question 3" },
        ],
        correctAnswer: "d",
      },
      {
        question: "What is the answer to question 4 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 4" },
          { id: "b", text: "Option B for question 4" },
          { id: "c", text: "Option C for question 4" },
          { id: "d", text: "Option D for question 4" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 5 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 5" },
          { id: "b", text: "Option B for question 5" },
          { id: "c", text: "Option C for question 5" },
          { id: "d", text: "Option D for question 5" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 6 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 6" },
          { id: "b", text: "Option B for question 6" },
          { id: "c", text: "Option C for question 6" },
          { id: "d", text: "Option D for question 6" },
        ],
        correctAnswer: "b",
      },
      {
        question: "What is the answer to question 7 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 7" },
          { id: "b", text: "Option B for question 7" },
          { id: "c", text: "Option C for question 7" },
          { id: "d", text: "Option D for question 7" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 8 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 8" },
          { id: "b", text: "Option B for question 8" },
          { id: "c", text: "Option C for question 8" },
          { id: "d", text: "Option D for question 8" },
        ],
        correctAnswer: "c",
      },
      {
        question: "What is the answer to question 9 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 9" },
          { id: "b", text: "Option B for question 9" },
          { id: "c", text: "Option C for question 9" },
          { id: "d", text: "Option D for question 9" },
        ],
        correctAnswer: "a",
      },
      {
        question: "What is the answer to question 10 in quiz 1?",
        imageUrl: "/a.jpg",
        options: [
          { id: "a", text: "Option A for question 10" },
          { id: "b", text: "Option B for question 10" },
          { id: "c", text: "Option C for question 10" },
          { id: "d", text: "Option D for question 10" },
        ],
        correctAnswer: "b",
      },
    ],
  },
  //   {
  //     id: 1,
  //     title: "Quiz on Topic 1",
  //     thumbnail: "/a.jpg",
  //     questions: 10,
  //     plays: 725,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 1?",
  //         imageUrl: "/a.jpg",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //     ],
  //   },
  //   {
  //     id: 2,
  //     title: "Quiz on Topic 2",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+2",
  //     questions: 10,
  //     plays: 282,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 2?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //     ],
  //   },
  //   {
  //     id: 3,
  //     title: "Quiz on Topic 3",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+3",
  //     questions: 10,
  //     plays: 783,
  //     label: "Hot",
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 3?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //     ],
  //   },
  //   {
  //     id: 4,
  //     title: "Quiz on Topic 4",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+4",
  //     questions: 10,
  //     plays: 960,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 4?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //     ],
  //   },
  //   {
  //     id: 5,
  //     title: "Quiz on Topic 5",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+5",
  //     questions: 10,
  //     plays: 437,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 5?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //     ],
  //   },
  //   {
  //     id: 6,
  //     title: "Quiz on Topic 6",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+6",
  //     questions: 10,
  //     plays: 784,
  //     label: "Hot",
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 6?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //     ],
  //   },
  //   {
  //     id: 7,
  //     title: "Quiz on Topic 7",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+7",
  //     questions: 10,
  //     plays: 712,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 7?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //     ],
  //   },
  //   {
  //     id: 8,
  //     title: "Quiz on Topic 8",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+8",
  //     questions: 10,
  //     plays: 729,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 8?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //     ],
  //   },
  //   {
  //     id: 9,
  //     title: "Quiz on Topic 9",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+9",
  //     questions: 10,
  //     plays: 802,
  //     label: "Hot",
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 9?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //     ],
  //   },
  //   {
  //     id: 10,
  //     title: "Quiz on Topic 10",
  //     thumbnail: "https://via.placeholder.com/150?text=Quiz+10",
  //     questions: 10,
  //     plays: 261,
  //     label: null,
  //     questionSet: [
  //       {
  //         question: "What is the answer to question 1 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q1",
  //         options: [
  //           { id: "a", text: "Option A for question 1" },
  //           { id: "b", text: "Option B for question 1" },
  //           { id: "c", text: "Option C for question 1" },
  //           { id: "d", text: "Option D for question 1" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 2 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q2",
  //         options: [
  //           { id: "a", text: "Option A for question 2" },
  //           { id: "b", text: "Option B for question 2" },
  //           { id: "c", text: "Option C for question 2" },
  //           { id: "d", text: "Option D for question 2" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 3 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q3",
  //         options: [
  //           { id: "a", text: "Option A for question 3" },
  //           { id: "b", text: "Option B for question 3" },
  //           { id: "c", text: "Option C for question 3" },
  //           { id: "d", text: "Option D for question 3" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 4 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q4",
  //         options: [
  //           { id: "a", text: "Option A for question 4" },
  //           { id: "b", text: "Option B for question 4" },
  //           { id: "c", text: "Option C for question 4" },
  //           { id: "d", text: "Option D for question 4" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //       {
  //         question: "What is the answer to question 5 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q5",
  //         options: [
  //           { id: "a", text: "Option A for question 5" },
  //           { id: "b", text: "Option B for question 5" },
  //           { id: "c", text: "Option C for question 5" },
  //           { id: "d", text: "Option D for question 5" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 6 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q6",
  //         options: [
  //           { id: "a", text: "Option A for question 6" },
  //           { id: "b", text: "Option B for question 6" },
  //           { id: "c", text: "Option C for question 6" },
  //           { id: "d", text: "Option D for question 6" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 7 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q7",
  //         options: [
  //           { id: "a", text: "Option A for question 7" },
  //           { id: "b", text: "Option B for question 7" },
  //           { id: "c", text: "Option C for question 7" },
  //           { id: "d", text: "Option D for question 7" },
  //         ],
  //         correctAnswer: "a",
  //       },
  //       {
  //         question: "What is the answer to question 8 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q8",
  //         options: [
  //           { id: "a", text: "Option A for question 8" },
  //           { id: "b", text: "Option B for question 8" },
  //           { id: "c", text: "Option C for question 8" },
  //           { id: "d", text: "Option D for question 8" },
  //         ],
  //         correctAnswer: "c",
  //       },
  //       {
  //         question: "What is the answer to question 9 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q9",
  //         options: [
  //           { id: "a", text: "Option A for question 9" },
  //           { id: "b", text: "Option B for question 9" },
  //           { id: "c", text: "Option C for question 9" },
  //           { id: "d", text: "Option D for question 9" },
  //         ],
  //         correctAnswer: "b",
  //       },
  //       {
  //         question: "What is the answer to question 10 in quiz 10?",
  //         imageUrl: "https://via.placeholder.com/100?text=Q10",
  //         options: [
  //           { id: "a", text: "Option A for question 10" },
  //           { id: "b", text: "Option B for question 10" },
  //           { id: "c", text: "Option C for question 10" },
  //           { id: "d", text: "Option D for question 10" },
  //         ],
  //         correctAnswer: "d",
  //       },
  //     ],
  //   },
];

export default quizzes;
